//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CustID { get; set; }
        [DisplayName("First Name")]
        [Required]
        public string CustFName { get; set; }
        [DisplayName("Last Name")]
        [Required]
        public string CustLName { get; set; }
        [DisplayName("DOB"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required]
        public Nullable<System.DateTime> CustDOB { get; set; }
        [DisplayName("Gender")]
        public string CustGender { get; set; }
        [DisplayName("Gender")]
        public string CustGenderDesc {
            get { 
                switch (this.CustGender) {
                    case "M": return ("Male"); 
                    case "F": return ("Female");
                    default: return ("Unknown");
                }
            }
        }
        [DisplayName("Address")]
        public string CustStreet { get; set; }
        [DisplayName("State")]
        public string CustState { get; set; }
        [DisplayName("PostalCD")]
        public string CustPostalCD { get; set; }
        [DisplayName("Phone No.")]
        public string CustPhone { get; set; }
        [DisplayName("Mobile No.")]
        [Required]
        public string CustMobile { get; set; }
        [DisplayName("Email")]
        [Required]
        public string CustEmail { get; set; }
        [DisplayName("Note")]
        public string CustRemark { get; set; }
        [DisplayName("Registered Date")]
        [Required]
        public System.DateTime CustRegisterdDate { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual State State { get; set; }
        public string CustDesc
        {
            get
            {
                return (this.CustFName + " " + this.CustLName + "-" + this.CustMobile);
            }
        }
    }
}
