//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public int OrderNo { get; set; }
        [DisplayName("Ordered Date")]
        public System.DateTime OrderDate { get; set; }
        public int CustID { get; set; }
        public int TripID { get; set; }
        [DisplayName("No Of Passenger")]
        [Range(0, 100)]
        public decimal No_Of_Pass { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
