//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int TripId { get; set; }
        [DisplayName("Origin")]
        [Required]
        public string From { get; set; }
        [DisplayName("Destination")]
        [Required]
        public string To { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }
        [DisplayName("Price"), DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = true)]
        [Required]
        [Range(0.00, double.MaxValue)]
        public decimal Price { get; set; }
        [DisplayName("Trip Start Date"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required]
        public Nullable<System.DateTime> TripStartDate { get; set; }
        [DisplayName("Trip End Date"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required]
        public Nullable<System.DateTime> TripEndDate { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
